# This is a basic workflow to help you get started with Actions

name: DVR

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      distributions:
        description: 'Provide the playlist link:'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Prepare
        run: sudo apt install ffmpeg

      - name: Run DVR
        run: |
          ffmpeg -i "${{ github.event.inputs.distributions }}" -c copy ~/vid.mkv
      
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: ~/vid.mkv
          retention-days: 90
      
          
          
